bootblock-$(CONFIG_SOC_INTEL_COMMON_BLOCK_SA_XEON) += systemagent_early.c
romstage-$(CONFIG_SOC_INTEL_COMMON_BLOCK_SA_XEON) += systemagent_early.c
ramstage-$(CONFIG_SOC_INTEL_COMMON_BLOCK_SA_XEON) += systemagent_early.c
postcar-$(CONFIG_SOC_INTEL_COMMON_BLOCK_SA_XEON) += systemagent_early.c
ramstage-$(CONFIG_SOC_INTEL_COMMON_BLOCK_SA_XEON) += systemagent.c
romstage-$(CONFIG_SOC_INTEL_COMMON_BLOCK_SA_XEON) += memmap.c
ramstage-$(CONFIG_SOC_INTEL_COMMON_BLOCK_SA_XEON) += memmap.c
postcar-$(CONFIG_SOC_INTEL_COMMON_BLOCK_SA_XEON) += memmap.c
